Setup
joseph-w-valdez/ChatGPTStylerFE pull request #2
Opened 2024-03-24 10:15 UTC by Lambpato

2024-03-26 05:37 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/developers/page.tsx
> +const Devs: DevsTypes[] = [
let's move this to something like `src/data/devs,ts`

2024-03-26 05:38 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/developers/page.tsx
> +];
good data structure

2024-03-26 05:41 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +
remove this new line

2024-03-26 05:41 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <div className='w-full grid gap-10 md:grid-cols-2 px-6 md:px-10 py-12 md:py-24 bg-[#0A3C33] text-white'>
change this `div` to a `section` element

2024-03-26 05:42 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <div className='w-full grid gap-10 md:grid-cols-2 px-6 md:px-10 py-12 md:py-24 bg-[#05211C] text-white'>
change this `div` to a `section` element

2024-03-26 05:42 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +
remove this new line

2024-03-26 05:42 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <div className='grid justify-items-center gap-4 px-6 md:px-10 pt-24 md:pt-48 pb-12 md:pb-24'>
change this `div` to a `section` element

2024-03-26 05:44 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +                    Adding a new button to scroll to the top of the message
let's shorten this a bit to ` New button to scroll to the top of the message thread`

2024-03-26 05:45 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +
remove this new line

2024-03-26 05:45 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <div className='w-full grid gap-10 md:grid-cols-2 px-6 md:px-10 py-12 md:py-24 bg-[#4B9C8C] text-white'>
change this `div` to a `section` element

2024-03-26 05:46 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +
remove this new line

2024-03-26 05:46 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <div className='w-full p-6 md:px-10 md:py-12 bg-[#1A1A1A] text-white'>
change this `div` to a `section` element

2024-03-26 05:47 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/page.tsx
> +          <BottomNav />
is this the footer? if so, change it's name to `Footer`. It should also be a sibling to `Main` instead of within it

2024-03-26 05:48 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/BottomNav.tsx
> +export default function BottomNav() {
this appears to be the `Footer` so it should be renamed

2024-03-26 05:48 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/BottomNav.tsx
> +    <div className='w-full px-6 md:px-10 py-8'>
change `div` to `footer` element

2024-03-26 05:49 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/BottomNav.tsx
> +            </div>
we should pull these out into a `socials` component. if it's localized to the footer component, it can stay in this file. otherwise, we should make it an external component in case we want to use it

2024-03-26 05:51 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/BottomNav.tsx
> +              <Link href=''>Report Bugs</Link>
I know we said we may want an anonymous Google Form, but I think we should just get a permalink to the Discord server's #bugs channel and use it here

2024-03-26 05:55 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/assets/demos/DARKMODE_CODE_DEFAULT.gif
for all assets, rename them to snake_case (all lowercase letters, with words separated by underscores)

2024-03-26 05:57 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/favicon.ico
can't see this yet, but make sure it's our logo

2024-03-26 05:59 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/layout.tsx
> +    "The ultimate Chrome extension to effortlessly enhance ChatGPT's look and feel!",
nice change

2024-03-26 06:01 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/assets/logos/index.ts
we don't need this file at all

2024-03-26 06:02 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/NavBar.tsx
> +import { FourtyFiveStylerLogo } from '@/public/assets/logos';
change this to `import smallLogo from '@public/assets/logos/45x45_logo.png`

2024-03-26 06:03 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/NavBar.tsx
> +        <FourtyFiveStylerLogo className='h-10 w-10' />
update this to be an `Image` element with `src={smallLogo}`

2024-03-26 06:05 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/developers/interface.ts
can we just move these interfaces into `page.tsx`? do more files use this?

2024-03-26 06:06 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/install_button/interface.ts
> +export interface InstallButtonTypes {
what's this do?

2024-03-26 06:07 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/install_button/interface.ts
can we just define the interfaces in the component?

2024-03-26 06:08 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/components/install_button/props.tsx
can we consolidate this all in the component file?

2024-03-26 06:09 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/next.svg
delete this file

2024-03-26 06:09 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/vercel.svg
delete this file

2024-03-26 06:10 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/assets/logos/136x136_STYLER_LOGO.svg
rename to `small_logo.svg`

2024-03-26 06:11 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/assets/logos/363x363_STYLER_LOGO.svg
rename this to `large_logo.svg`

2024-03-26 06:11 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/public/assets/logos/45x45_STYLER_LOGO.svg
rename this to `small_logo.svg`

2024-03-26 06:18 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/developers/page.tsx
> +  const items = Devs.map((i) => (
does this map handle alternating the dev details left<-->right?

2024-03-27 00:54 UTC, Lambpato commented on chat-gpt-styler-fe/public/assets/logos/index.ts
this is to import the svg and not need an image element, im using the svgr webpack

2024-04-24 21:46 UTC, joseph-w-valdez commented
just noticed this project is nested in the `chat-gpt-styler-fe` directory. make sure to pull everything out of this directly into the root directory. that should fix the deployment issues.

2024-04-24 22:00 UTC, joseph-w-valdez commented on chat-gpt-styler-fe/app/developers/data.ts
can we move this file into `app/data/developers.ts`?

2024-04-26 16:05 UTC, KennethDelaCruz commented on app/developers/data.ts
> +    bio: `Kevin here! Full Stack Web Developer adept in JavaScript, React, HTML5, CSS3, PostgreSQL, and more. With a background in small business management, I've transitioned into tech, completing a
update Learning Fuze to LearningFuze

2024-04-26 16:06 UTC, KennethDelaCruz commented on app/developers/data.ts
> +    key: 1,
just so i can get a better understanding, what is the `key` used for?

2024-04-26 16:16 UTC, KennethDelaCruz commented on app/page.tsx
> +              <p className='text-lg'>Windows and MacOS</p>
we can remove this for now since we dont have an extension for Windows or MacOS.

We can add it in the future when we release 😄

2024-04-26 16:20 UTC, KennethDelaCruz commented on components/InstallButton.tsx
> +}
![Screenshot 2024-04-26 at 9 17 29 AM](https://github.com/joseph-w-valdez/ChatGPTStylerFE/assets/69921839/ec7f6de5-c049-464a-9fb4-c2c9110f3ee9)

I think this is the component for the image above. But we can adjust this from a Dropdown to a button since we dont have any other browser extension. then we can refactor later when we release the others 😄

2024-04-26 16:22 UTC, KennethDelaCruz commented on components/InstallButton.tsx
> +    id: 1,
im assuming this property is used as `index` when mapping through. 

we can declare this at the`.map` function using `(option: OptionType, index: number) => {}`

2024-04-26 16:23 UTC, KennethDelaCruz commented on components/InstallButton.tsx
> +  const items = options.map((i) => (
```suggestion
  const items = options.map((option: OptionType, index: number) => (
```

then adjust the type and remove `id`

2024-04-26 16:24 UTC, KennethDelaCruz commented on public/assets/developers_pfps/joseph_valdez.png
update this picture pls. 


jk LOL

2024-04-26 16:27 UTC, KennethDelaCruz commented on app/developers/page.tsx
> +  const items = Devs.map((i) => (
```suggestion
  const items = Devs.map((dev: DevTypes, index: number) => (
```

then maybe we can do a ` const key = index + 1` so we dont mess up the logic below and we dont have to declare `id` in the type

2024-04-26 16:29 UTC, KennethDelaCruz requested changes
left some comments for some changes

2024-04-26 16:30 UTC, KennethDelaCruz commented on app/page.tsx
> +              <p className='text-lg'>Windows and MacOS</p>
resolving, clarified with Valdez. Informed me that it does work for Windows and MacOS mb mb lol

2024-04-26 16:54 UTC, joseph-w-valdez commented on app/developers/page.tsx
> +      <DevBios Devs={Devs} />
I think it's fine to just move all of `DevBios` mapping content inside of here.

2024-04-26 16:56 UTC, joseph-w-valdez requested changes
changes requested. also remember to add hover responsiveness and `aria-labels` for all buttons and links.

2024-04-26 16:57 UTC, KennethDelaCruz commented on app/developers/page.tsx
> +export default function Page() {
also with some discussion with @joseph-w-valdez 

We can update all `Page` components to something relative that its display. For this example, we change `Page` to `DevPage`. 

It should work as long as its the default export of the `page.tsx` file

2024-04-29 00:34 UTC, Lambpato commented on app/developers/data.ts
> +    key: 1,
map would tweak out about it needing a key but i've since removed the key property and just used the index number for the map key

2024-11-24 20:49 UTC, joseph-w-valdez approved these changes

2024-11-24 21:00 UTC, merged